# arxivの学問領域の指定
subject: 'cat:cs.IR  OR cat:cs.SE'

# 検索キーワード
keywords:
        bug localization: 5
        feature location: 3
        cross-language: 3
        bug reports: 2
        bug: 1
        deep: -3
        machine learning: -3

# 通知の閾値
score_threshold: 0
